# Site settings
title: Mallorentec, el blog de Miguel A. Llorente
email: mallorente@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Un lugar para depositar reflexiones sobre el día a día.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mallorentec.com" # the base hostname & protocol for your site
twitter_username: mallorentec
github_username:  mallorente

# Build settings
markdown: kramdown
